# Generated by Django 5.1 on 2024-11-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
