# Generated by Django 5.1 on 2024-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_vehicle_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
