# Generated by Django 5.1 on 2024-11-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_vehicle_image_alter_vehicle_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
